version: "3.4"
services:
  piko-1:
    image: ghcr.io/andydunstall/piko:latest
    command:
      - server
      - --config.path
      - /etc/piko.yaml
      - --cluster.node-id-prefix
      - piko-1-
    hostname: piko-1
    volumes:
      - ./config/piko.yaml:/etc/piko.yaml


  piko-2:
    image: ghcr.io/andydunstall/piko:latest
    command:
      - server
      - --config.path
      - /etc/piko.yaml
      - --cluster.node-id-prefix
      - piko-2-
    hostname: piko-2
    volumes:
      - ./config/piko.yaml:/etc/piko.yaml


  piko-3:
    image: ghcr.io/andydunstall/piko:latest
    command:
      - server
      - --config.path
      - /etc/piko.yaml
      - --cluster.node-id-prefix
      - piko-3-
    hostname: piko-3
    volumes:
      - ./config/piko.yaml:/etc/piko.yaml


  piko-4:
    image: ghcr.io/andydunstall/piko:latest
    command:
      - server
      - --config.path
      - /etc/piko.yaml
      - --cluster.node-id-prefix
      - piko-4-
    hostname: piko-4
    volumes:
      - ./config/piko.yaml:/etc/piko.yaml


  piko-5:
    image: ghcr.io/andydunstall/piko:latest
    command:
      - server
      - --config.path
      - /etc/piko.yaml
      - --cluster.node-id-prefix
      - piko-5-
    hostname: piko-5
    volumes:
      - ./config/piko.yaml:/etc/piko.yaml


  piko-6:
    image: ghcr.io/andydunstall/piko:latest
    command:
      - server
      - --config.path
      - /etc/piko.yaml
      - --cluster.node-id-prefix
      - piko-6-
    hostname: piko-6
    volumes:
      - ./config/piko.yaml:/etc/piko.yaml


  load-balancer:
    image: caddy:latest
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - "piko-1"
      - "piko-2"
      - "piko-3"
      - "piko-4"
      - "piko-5"
      - "piko-6"
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002


  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --log.level=error
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
    depends_on:
      - "piko-1"
      - "piko-2"
      - "piko-3"
    ports:
      - 9090:9090


  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_LOG_MODE=console
      - GF_LOG_LEVEL=critical
    ports:
      - 3000:3000


networks:
  piko-network:
    driver: bridge
    name: piko-network